// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SQLReplicator.BDDTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TrackingChangesFeature : object, Xunit.IClassFixture<TrackingChangesFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "TrackingChanges", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TrackingChanges.feature"
#line hidden
        
        public TrackingChangesFeature(TrackingChangesFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Insertion in Orders table is tracked in OrdersChanges table")]
        [Xunit.TraitAttribute("FeatureTitle", "TrackingChanges")]
        [Xunit.TraitAttribute("Description", "Insertion in Orders table is tracked in OrdersChanges table")]
        public async System.Threading.Tasks.Task InsertionInOrdersTableIsTrackedInOrdersChangesTable()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Insertion in Orders table is tracked in OrdersChanges table", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
 await testRunner.GivenAsync("database \"DB4\" does not have a trigger for table \"Orders\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 5
 await testRunner.AndAsync("database \"DB4\" does not have a change tracking table for table \"Orders\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "AttributeName"});
                table13.AddRow(new string[] {
                            "OrderID"});
                table13.AddRow(new string[] {
                            "ProductID"});
#line 6
 await testRunner.WhenAsync("I run CreateTrigger service on database \"DB4\" for table \"Orders\" with key attribu" +
                        "tes:", ((string)(null)), table13, "When ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "AttributeName"});
                table14.AddRow(new string[] {
                            "OrderID"});
                table14.AddRow(new string[] {
                            "ProductID"});
#line 10
 await testRunner.AndAsync("I run CreateChangeTrackingTable service on database \"DB4\" for table \"Orders\" with" +
                        " key attributes:", ((string)(null)), table14, "And ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "OrderID",
                            "ProductID",
                            "CustomerName",
                            "Quantity"});
                table15.AddRow(new string[] {
                            "998",
                            "924124",
                            "Tom Hanks",
                            "12"});
#line 14
 await testRunner.AndAsync("I insert new row in database \"DB4\" table \"Orders\" with values:", ((string)(null)), table15, "And ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "OrderID",
                            "ProductID",
                            "Operation"});
                table16.AddRow(new string[] {
                            "998",
                            "924124",
                            "I"});
#line 17
 await testRunner.ThenAsync("the table \"OrdersChanges\" in database \"DB4\" should have row with values:", ((string)(null)), table16, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Deletion in Orders table is tracked in OrdersChanges table")]
        [Xunit.TraitAttribute("FeatureTitle", "TrackingChanges")]
        [Xunit.TraitAttribute("Description", "Deletion in Orders table is tracked in OrdersChanges table")]
        public async System.Threading.Tasks.Task DeletionInOrdersTableIsTrackedInOrdersChangesTable()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Deletion in Orders table is tracked in OrdersChanges table", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
 await testRunner.GivenAsync("database \"DB4\" does not have a trigger for table \"Orders\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 23
 await testRunner.AndAsync("database \"DB4\" does not have a change tracking table for table \"Orders\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "AttributeName"});
                table17.AddRow(new string[] {
                            "OrderID"});
                table17.AddRow(new string[] {
                            "ProductID"});
#line 24
 await testRunner.WhenAsync("I run CreateTrigger service on database \"DB4\" for table \"Orders\" with key attribu" +
                        "tes:", ((string)(null)), table17, "When ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "AttributeName"});
                table18.AddRow(new string[] {
                            "OrderID"});
                table18.AddRow(new string[] {
                            "ProductID"});
#line 28
 await testRunner.AndAsync("I run CreateChangeTrackingTable service on database \"DB4\" for table \"Orders\" with" +
                        " key attributes:", ((string)(null)), table18, "And ");
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "OrderID",
                            "ProductID",
                            "CustomerName",
                            "Quantity"});
                table19.AddRow(new string[] {
                            "999",
                            "924125",
                            "Tom Hanks",
                            "13"});
#line 32
 await testRunner.AndAsync("I delete existing row in database \"DB4\" table \"Orders\" with values:", ((string)(null)), table19, "And ");
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "OrderID",
                            "ProductID",
                            "Operation"});
                table20.AddRow(new string[] {
                            "999",
                            "924125",
                            "D"});
#line 35
 await testRunner.ThenAsync("the table \"OrdersChanges\" in database \"DB4\" should have row with values:", ((string)(null)), table20, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Update in Orders table is tracked in OrdersChanges table")]
        [Xunit.TraitAttribute("FeatureTitle", "TrackingChanges")]
        [Xunit.TraitAttribute("Description", "Update in Orders table is tracked in OrdersChanges table")]
        public async System.Threading.Tasks.Task UpdateInOrdersTableIsTrackedInOrdersChangesTable()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Update in Orders table is tracked in OrdersChanges table", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 39
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 40
 await testRunner.GivenAsync("database \"DB4\" does not have a trigger for table \"Orders\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 41
 await testRunner.AndAsync("database \"DB4\" does not have a change tracking table for table \"Orders\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "AttributeName"});
                table21.AddRow(new string[] {
                            "OrderID"});
                table21.AddRow(new string[] {
                            "ProductID"});
#line 42
 await testRunner.WhenAsync("I run CreateTrigger service on database \"DB4\" for table \"Orders\" with key attribu" +
                        "tes:", ((string)(null)), table21, "When ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "AttributeName"});
                table22.AddRow(new string[] {
                            "OrderID"});
                table22.AddRow(new string[] {
                            "ProductID"});
#line 46
 await testRunner.AndAsync("I run CreateChangeTrackingTable service on database \"DB4\" for table \"Orders\" with" +
                        " key attributes:", ((string)(null)), table22, "And ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "OrderID",
                            "ProductID",
                            "CustomerName",
                            "Quantity"});
                table23.AddRow(new string[] {
                            "1",
                            "101",
                            "Alice Johnson",
                            "2"});
#line 50
 await testRunner.AndAsync("I update existing row in database \"DB4\" table \"Orders\" with values:", ((string)(null)), table23, "And ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "OrderID",
                            "ProductID",
                            "Operation"});
                table24.AddRow(new string[] {
                            "1",
                            "101",
                            "D"});
#line 53
 await testRunner.ThenAsync("the table \"OrdersChanges\" in database \"DB4\" should have row with values:", ((string)(null)), table24, "Then ");
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "OrderID",
                            "ProductID",
                            "Operation"});
                table25.AddRow(new string[] {
                            "1",
                            "101",
                            "I"});
#line 56
 await testRunner.AndAsync("the table \"OrdersChanges\" in database \"DB4\" should have row with values:", ((string)(null)), table25, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await TrackingChangesFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await TrackingChangesFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
